
  development:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: enginectrainspectionform
    pool: 5
    username: root
    password: 12341234
    socket: /opt/local/var/run/mysql5/mysqld.sock
  test:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: enginectrainspectionform
    pool: 5
    username: root
    password: 12341234
    socket: /opt/local/var/run/mysql5/mysqld.sock

  production:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: enginectrainspectionform
    pool: 5
    username: root
    password: 12341234
    socket: /opt/local/var/run/mysql5/mysqld.sock
